;;; ~/.doom.d/userconfig/theme-colors.el -*- lexical-binding: t; -*-

(defun db/extract-theme-colors (&optional theme)
  "Extract colors from the current theme."
  (interactive)
  (setq THEME_BG (face-background 'default))
  (setq THEME_FG (face-foreground 'default))
  (setq THEME_B0 (face-foreground 'highlight))
 ; (setq THEME_B1 (face-background 'highlight-indentation-current-column-face))
  (setq THEME_B2 (face-background 'region))
  (setq THEME_B3 (face-background 'tooltip))
  (setq THEME_B4 (face-foreground 'fringe))
  (setq THEME_B5 (face-background 'shadow))
  (setq THEME_B6 (face-foreground 'font-lock-comment-face))
  (setq THEME_B7 (face-foreground 'line-number-current-line))
  (setq THEME_B8 (face-foreground 'lazy-highlight))

  (setq THEME_RED (face-foreground 'font-lock-preprocessor-face))
  (setq THEME_ORANGE (face-foreground 'font-lock-warning-face))
  (setq THEME_GREEN (face-foreground 'font-lock-function-name-face))
  (setq THEME_YELLOW (face-foreground 'font-lock-string-face))
  (setq THEME_VIOLET (face-foreground 'font-lock-constant-face))
  (setq THEME_CYAN (face-foreground 'font-lock-type-face))

  (setenv "EMACS_THEME_BG" THEME_BG)
  (setenv "EMACS_THEME_FG" THEME_FG)
  (setenv "EMACS_THEME_B0" THEME_B0)
 ; (setenv "EMACS_THEME_B1" THEME_B1)
  (setenv "EMACS_THEME_B2" THEME_B2)
  (setenv "EMACS_THEME_B3" THEME_B3)
  (setenv "EMACS_THEME_B4" THEME_B4)
  (setenv "EMACS_THEME_B5" THEME_B5)
  (setenv "EMACS_THEME_B6" THEME_B6)
  (setenv "EMACS_THEME_B7" THEME_B7)
  (setenv "EMACS_THEME_B8" THEME_B8)

  (setenv "EMACS_THEME_RED" THEME_RED)
  (setenv "EMACS_THEME_ORANGE" THEME_ORANGE)
  (setenv "EMACS_THEME_GREEN" THEME_GREEN)
  (setenv "EMACS_THEME_YELLOW" THEME_YELLOW)
  (setenv "EMACS_THEME_VIOLDET" THEME_VIOLET)
  (setenv "EMACS_THEME_CYAN" THEME_CYAN))

(advice-add 'enable-theme :after #'db/extract-theme-colors)
