# set permissions
xhost +SI:localuser:$USER

# set fallback cursor
xsetroot -cursor_name left_ptr

# set keyboard repeat rate
xset r rate 200 60

# load resources
xrdb -load "$XDG_CONFIG_HOME"/X11/Xresources &

# Launch emacs
exec dbus-launch --exit-with-session emacs -mm
