;;; ../../.local/share/git/dotArch/.config/doom/userconfig/screenshot.el -*- lexical-binding: t; -*-

(defun db/screenshot (ext tmp-dir tmp-name)
  "Interactive menu for screenshots. Requires main, xsel, xclip and curl to be installed."
  (interactive)
  (let* ((actions '("Section" "Whole Screen"))
        (targets '("Imgur" "Clipboard" "Locally"))
        (tmp-file (concat tmp-dir tmp-name "." ext)))

    (setq action (completing-read "Take screenshot of ..." actions )
          target (completing-read "Save screenshot ..." targets ))
    (setq result (db/screenshot-return-cmd action target tmp-file ext))
    (sit-for 0)
    (call-process-shell-command (nth 1 result) nil nil nil)
    (cond ((equal target "Locally")
           (message (concat "Image saved to: " (nth 0 result))))
          ((equal target "Imgur")
           (message "Image uploaded to Imgur. URL saved to the clipboard."))
          ((equal target "Clipboard")
           (message "Image saved to the clipboard.")))))

(defun db/screenshot-return-cmd (source target tmp-file ext)
  "Build the command to be executed for taking screenshots."
  (let ((cmd ""))
    (cond ((equal source "Section")
           (cond ((equal target "Locally")
                  (setq tmp-file (concat (read-directory-name "Select directory: " "~/") (read-string "File name (Without extension): ") "." ext))
                  (setq cmd (concat "maim -u -s " tmp-file)))
                 ((equal target "Imgur")
                  (setq cmd (concat "maim -u -s " tmp-file "; imgur " tmp-file " | xclip -selection clipboard")))
                 ((equal target "Clipboard")
                  (setq cmd (concat "maim -u -s | xclip -selection clipboard -t image/png")))))
          ((equal source "Whole Screen")
           (cond ((equal target "Locally")
                  (setq tmp-file (concat (read-directory-name "Select directory: " "~/") (read-string "File name (Without extension): ") "." ext))
                  (setq cmd (concat "maim -u " tmp-file)))
                 ((equal target "Imgur")
                  (setq cmd (concat "maim -u " tmp-file "; imgur " tmp-file " | xclip -selection clipboard")))
                 ((equal target "Clipboard")
                  (setq cmd (concat "maim -u | xclip -selection clipboard -t image/png"))))))
    (list tmp-file cmd)))

(global-set-key [print] (lambda () (interactive) (db/screenshot "png" "/tmp/" "screenshot")))
